name: enchantment_unlimit
version: '1.1'
main: io.github.freecad1211.enchantment_unlimit.EnchantmentUnlimit
api-version: '1.21'
commands:
  unlimitenchant:
    description: 특정 플레이어의 손에 든 아이템에 인챈트를 적용합니다.
    aliases: [ue]
    permission: enchantment_unlimit.admin
    usage: /<command> <닉네임> <인챈트> <레벨>
  enchantment_unlimit:
    description: 플러그인 설정 관리
    aliases: [eu]
    permission: enchantment_unlimit.admin
    usage: /<command> reload
permissions:
  enchantment_unlimit.admin:
    description: EnchantmentUnlimit 플러그인 관리자 권한
    default: op
